### ISSUE TITLE
browsers polyfill

### ISSUE THREAD

**Issue by JiLiZART** [dfilatov/vow#102]
Any plans to polyfill or use build-in `Promise` ?

**Comment by dfilatov** [comment]
What for? Is there any valuable reason (exluding "wow, native promise") to do that?
What's more, it's not possible to implement some of features via native promise, for instance, synchronously get a value of already resolved promise.

**Comment by JiLiZART** [comment]
Currently i use vow with bem-core, plus some libs, thats use Promise, but
IE don't have any support for it. Its would be useful if i can use only one
Promise lib in whole project, rather than use polyfill, doing the same job
as vow.
Ср, 25 мая 2016 в 11:02, Filatov Dmitry <notifications@github.com>:

**Comment by dfilatov** [comment]
As I wrote before, unfortunately, there's no way to implement all of vow api on top of native promises api.

**Comment by Guria** [comment]
@dfilatov I think @JiLiZART do not ask to implement `vow` api on top of native promises, but instead use  `vow` as polyfill. So if current environment doesn't have native Promise it could be polyfilled with `vow`.

**Comment by Guria** [comment]
@JiLiZART have you tried smth like `window.Promise = window.Promise || vow.Promise` ?

**Comment by JiLiZART** [comment]
@Guria no, i'll try

**Comment by Guria** [comment]
@JiLiZART 
seems to work pretty well: https://tonicdev.com/guria/57456b06a9e8791200e21800

**Comment by dfilatov** [comment]
Vow should properly work as a polyfill for native promises. Let me know if it doesn't.
