### ISSUE TITLE
Проблема с промисами в новых Chromium-ах

### ISSUE THREAD

**Issue by chestozo** [dfilatov/vow#106]
Привет.
Обнаружилась проблема в новых браузерах (к примеру, воспроизводится на нашем проекте в Opera 41.0.2353.46 - кажется, это developer версия). Кейс сложный, тест пока не смог вычленить.

Вначале всё хорошо и вот такой скрипт:
```js
vow.all([]).then(
    function() { console.log('fsm', true); },
    function() { console.log('fsm', false); }
);
```
отрабатывает правильно:
![image](https://cloud.githubusercontent.com/assets/498934/19976448/bfcead8e-a200-11e6-80ee-1201a43a1c17.png)

Но в какой-то момент получаем такую картину:
![image](https://cloud.githubusercontent.com/assets/498934/19976476/ea2065b4-a200-11e6-9b68-d404f1951a86.png)

Отдельно взятый промис тоже сломан:
![image](https://cloud.githubusercontent.com/assets/498934/19976530/217a6aa0-a201-11e6-88c0-aaaaf726ca00.png)

Постараюсь допилить тест, но хотелось как можно раньше зарепортить, вдруг будут какие-то идеи. Кажется, в последнем Chrome поведение такое же, но пока у меня получилось воспроизвести только в Opera.

**Comment by dfilatov** [comment]
Ты точно используешь последнюю, 0.4.13, версию?

**Comment by chestozo** [comment]
о! мы сидим вообще не `0.4.7`.
Обновимся, посмотрим, как чего.
Спасибо!
