### ISSUE TITLE
window.postMessage is throttling in Safari

### ISSUE THREAD

**Issue by narqo** [dfilatov/vow#84]
See YuzuJS/setImmediate#41 for discussion.

It looks like polyfill based on `MessageChannel` works up to 10 times faster in some browsers.

**Comment by dfilatov** [comment]
As far as I understand they decided there's no problem )

**Comment by narqo** [comment]
As far as I understood, there is no such problem in new Safari 8, under the OSX Yosemite. But the problem is with Safari 7.x which comes with Mavericks :(

**Comment by dfilatov** [comment]
Since 0.4.10 `MutationObserver` has been using for internal "next tick" operations. According to http://caniuse.com/#search=MutationObserver it is supported by Safari 7 and should work much "faster" than `postMessage`.
