### ISSUE TITLE
Can you please unpublish the pi package?

### ISSUE THREAD

**Issue by IonicaBizau** [dfilatov/vow#87]
It seems like the `pi` is not maintained anymore and the project name was changed.

So, could you please unpublish [`pi`](https://www.npmjs.com/package/pi) and let me publish the current [`pi-number`](https://www.npmjs.com/package/pi-number) package there?

Thanks!

**Comment by dfilatov** [comment]
@IonicaBizau done

**Comment by IonicaBizau** [comment]
Thanks a lot! :+1:
